using System;
using System.Drawing;
using System.Windows.Forms;


namespace Mandelbrot_Namespace {
	class Mandebrot_class : Form {
		private Label m_ExampleLabel;
		public Mandebrot_class() {
			InitializeComponent();
		}
		// Don't change this, auto generated by the designer
		private void InitializeComponent() {
			m_ExampleLabel = new Label();
			RenderButton = new Button();
			label1 = new Label();
			textBox1 = new TextBox();
			SuspendLayout();
			// 
			// m_ExampleLabel
			// 
			m_ExampleLabel.Location = new Point(22, 19);
			m_ExampleLabel.Name = "m_ExampleLabel";
			m_ExampleLabel.Size = new Size(100, 20);
			m_ExampleLabel.TabIndex = 0;
			m_ExampleLabel.Text = "HI";
			m_ExampleLabel.Click += m_ExampleLabel_Click;
			// 
			// RenderButton
			// 
			RenderButton.Location = new Point(255, 19);
			RenderButton.Name = "RenderButton";
			RenderButton.Size = new Size(94, 29);
			RenderButton.TabIndex = 1;
			RenderButton.Text = "Render";
			RenderButton.UseVisualStyleBackColor = true;
			RenderButton.Click += RenderButton_Click;
			// 
			// label1
			// 
			label1.AutoSize = true;
			label1.Location = new Point(169, 229);
			label1.Name = "label1";
			label1.Size = new Size(0, 20);
			label1.TabIndex = 2;
			// 
			// textBox1
			// 
			textBox1.Location = new Point(87, 13);
			textBox1.Name = "textBox1";
			textBox1.Size = new Size(125, 27);
			textBox1.TabIndex = 3;
			textBox1.TextChanged += textBox1_TextChanged;
			// 
			// Mandebrot_class
			// 
			ClientSize = new Size(420, 520);
			Controls.Add(textBox1);
			Controls.Add(label1);
			Controls.Add(RenderButton);
			Controls.Add(m_ExampleLabel);
			Name = "Mandebrot_class";
			ResumeLayout(false);
			PerformLayout();
		}

		private void RenderButton_Click(object sender, EventArgs e) {

		}
		private Label label1;
		private TextBox textBox1;
		private Button RenderButton;

		private void textBox1_TextChanged(object sender, EventArgs e) {

		}

		private void m_ExampleLabel_Click(object sender, EventArgs e) {

		}
	}
}

